### ISSUE TITLE
MQTT publish motion/snapshot doesn't match motion event.

### ISSUE THREAD

**Issue by reefland** [EliasKotlyar/Xiaomi-Dafang-Hacks#1628]
* exact camera hardware:  Wyzecam v2
* the Xiaomi-Dafang-Hacks commitid:  ede5abe ( No update available)

### Description
Summary: The image I pull from motion/snapshot is always from a previous event.  The image I'm expecting "now" doesn't show up until the next motion event.

I followed integration guide for MQTT:
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/integration/homeassistant/homeassistant.md

Worked perfectly. Thank for excellent guide.  based on this statement:

_You should now be getting messages on topic myhome/mycamera/motion and images on myhome/mycamera/motion/snapshot/image while myhome/mycamera/motion/detection is set to ON._

I created this automation Home Assistant which upon topic trigger of "motion" saves the "motion/snapshot" to disk, waits a few seconds and send an alert with image.   The image has OSD enabled with timestamp and HA is adding timestamp to alert.
```
alias: CAMERA Notify MOTION on MQTT
description: Sends motion notification and image from MQTT topic
trigger:
  - platform: mqtt
    topic: myhome/outside_cam/motion
    payload: 'ON'
condition: []
action:
  - service: camera.snapshot
    data_template:
      filename: '/tmp/snapshot_{{ trigger.topic.split(''/'')[-2] }}.jpg'
    entity_id: camera.outside_cam_motion_snapshot
  - delay: '00:00:05'
  - service: notify.slack_notify
    data_template:
      message: >-
        Motion Detected by {{ trigger.topic.split('/')[-2] }} at
        {{now().strftime('%m-%d-%Y %H:%M:%S')}}
      data:
        file:
          path: '/tmp/snapshot_{{ trigger.topic.split(''/'')[-2] }}.jpg'
mode: single
```
All of the above works great, except when I view the image in the alert the timestamp doesn't line up.  I don't mean its off by a few seconds. It's off by whatever the last event was.  For example if at 08:00 a motion event was triggered it will have the image of the previous event.  If at 8:15 a motion event is triggered it will have the image from the 08:00 event.  I can't get this in sync.

### What did you do to debug the issue

I added the 5 second pause in case there was some delay in writing the image.

I tried making the trigger topic `myhome/outside_cam/motion/snapshot` with payload "None" (otherwise it tried to decode the payload) and seemed to get more images, but still out of sync. 

I've since switched to trigger based on MQTT binary sensor for cam motion and just grab a new camera.snapshot image and time stamps are within 1 second of each other. This is fine, but I don't understand why the above automation does not work as expected.

### Evidence

![mqtt_sync_01](https://user-images.githubusercontent.com/16230914/99908840-ebfd9f00-2cb2-11eb-8b92-987db4f35ec5.png)

As described, the timestamp of the alert is right.  The image timestamp is from previous alert.  Ignore the "Kitchen" vs "outside"... it normally looks outside the kitchen window.

```
# free
              total        used        free      shared  buff/cache   available
Mem:          99536       23584       45636           0       30316           0
-/+ buffers/cache:        23584       75952
Swap:         16380           0       16380
```
Being that I don't have an error, not sure what log would be relevant.

### Contribute Back

If your issue was resolved, please consider contributing back to the project by creating a pull request to improve the code or documentation in order to avoid that this issue arises again for other people.
