### ISSUE TITLE
Home assistant automation to send image

### ISSUE THREAD

**Issue by fotiDim** [EliasKotlyar/Xiaomi-Dafang-Hacks#614]
I am trying to setup an automation that takes a camera image and sends it through telegram. Cannot figure out how. This should be added to the HA guide. The same applies to getting the image from mqtt and attaching it to a Telegram message.

**Comment by jmtatsch** [comment]
I would also be very interested in getting this to work.

I came up with the following, but it doesn't even trigger an event upon getting a new snapshot:

```
  id: '1523685773659'
  alias: 'New snapshot received'
  trigger:
    platform: mqtt
    topic: mylocation/dafang1/motion/snapshot
  action:
    service: notify.me
    data:
      title: 'New snapshot'
      message: "received."
      data:
        photo:
          buffer: trigger.event.data
```

and in https://github.com/home-assistant/home-assistant/blob/b7c336a687356c8f4f81bbfd2f1b53af7b94c250/homeassistant/components/telegram_bot/__init__.py#L537

We would also need to enable the Telegram component to deal with a binary blob / buffer input instead of paths/urls somehow like this:

```
buffer = kwargs.get(ATTR_BUFFER)
if buffer is not None:
  file_content = buffer
else:
  file_content = load_data(...)
```

**Comment by olskar** [comment]
It would be nice just to know how to get a snapshot url that one can use in home assistant

**Comment by thawizard** [comment]
i have a working snapshot request via telegram until fanghacks implemented ssl/https.  i did not inspect further what the problem is but i might look at it again.

**Comment by olskar** [comment]
@thawizard I guess telegram wont accept the certificate, the same issue as with all browsers that does not trust the certificate the camera generates

**Comment by fotiDim** [comment]
Can you please share your automation? 

Another solution that I am thinking of is to store the images in folder on HA, which I wanted to do anyway, and then sent them from there directly.

**Comment by thawizard** [comment]
I have it tested again there was a mistake on my side.it works just fine by pulling currentimage.cgi
I'll share my config later tonight when I'm back home .

**Comment by thawizard** [comment]
Okay, i got a bit of time now. These are my config
 
configuration.yaml
```
ffmpeg: ## is necessary to enable ffmpeg in home assistant 
camera:
  - platform: ffmpeg
    name: Dafang
    input: -rtsp_transport tcp -i rtsp://user:pw3@camera.ip:8554/unicast
```

Here is a simplified automation to request an image with a Telegram command /dafang (working telegram bot and telegram polling config is needed)
 
automation.yaml     
```
- id: telegram_dafang
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/dafang'
  action:
  - service: notify.telegram_cam
    data_template:
      message: Message
      data: 
        photo:
          url: 'https://hassip.ip:port{{states.camera.dafang.attributes.entity_picture}}'
          caption: '{{now().strftime("%d.%m.%Y-%H:%M:%S")}}'
```
For `{{states.camera.dafang.attributes.entity_picture}} ` please change "camera.dafang" into your own setting. You can find the correct one by checking entity list in your hass-io (https://hassio.ip:port/dev-state/).
the camera attribute `entity_picture` is the same as this `/api/camera_proxy/camera.dafang?token=##hash##` in which the token-hash changes all the time on a new image load. So in that case, the current image will be pulled and sent via Telegram.

I have a couple Camera automations running, but this might be the most useful - this tells me about a movement in our house when nobody is at home (could be either through camera sensor or any binary sensor) and additionally send me a current image.

```
- id: sensor-on-warn-telegram
  trigger:
  - entity_id: group.motionsensor
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: group.mobiledevices
    state: not_home
  action:
  - service: notify.telegram_warn
    data_template:
      message: Movement detected.
      data: 
        photo:
          url: 'https://hassip.ip:port{{states.camera.dafang.attributes.entity_picture}}'
          caption: '{{now().strftime("%d.%m.%Y-%H:%M:%S")}}'
  - service: notify.telegram_warn
    data_template:
      message: Something's moving. Could it be a raccoon? Please check your home.
```
I have also created multiple commands which I can send through Telegram, for example if I enter /dafang-rtsp-restart it will stop and start rtsp again  Few other commands are to start/stop/restart mqttcontrol or mqttstatus... It sends the corresponding cgi command locally through home assistant but thats another topic.

Feel free to ask, if you like to know anything else...
